spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  sql:
    init:
      data-locations: classpath*:db/h2/
      mode: always
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
    defer-datasource-initialization: true  # 데이터 소스 초기화 지연 설정
  #    open-in-view: true
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    org:
      hibernate:
        #        SQL: debug           # jpa 설정에서 쿼리를 보여주므로 필요 없음.
        type:
          descriptor:
            sql:
              BasicBinder: trace
#jwt
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420