spring:
## mysql db
  h2:
    console:
      enabled: true
      path:
  datasource:
    url: jdbc:mysql://${AWS_RDS_URL}/wrieatingdb
    username: admin
    password: ${AWS_RDS_PASSWORD}
    driver-class-name:
  sql:
    init:
      data-locations:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
#  h2 db
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
#  sql:
#    init:
#      data-locations: classpath*:db/h2/
#      mode: always
#  jpa:
#    hibernate:
      #####
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${email}
#    password: ${password}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#email:
#  sender:
#    man: ${email}
#    password: ${password}

#jwt
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420

server:
  error:
    whitelabel:
      enabled: false
